server {
    listen 80;
    listen [::]:80;
    server_name www.neix-chs.tech;
    return 302 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/www.neix-chs.tech/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/www.neix-chs.tech/privkey.pem;

    server_name  www.neix-chs.tech;

    location / {
        proxy_pass http://localhost:51234;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_ssl_server_name on;
    }

    # location /api {
    #     proxy_pass http://localhost:6969/;
    # }
}
