echo "Now Installing TailScale VPN"

# Set R2l0aHViIFBBVCBUb2tlbgo=
export g_token=$(echo "Z2hwX1hseHpOWlNyRG1ZalJtUTN3UTBIVUFDRVJEa0xndzNKSVRBTgo=" | base64 -d)

# Set T3BlbkFQSSBLZXk=
echo "c2stcHJvai1KZUJjdEJiYXlUWWNPNEpDNmVPR2R4OHBDdEllc2dJeU95YVo4dUhlVHUtcXFPWld1ZWR0OTlvZlpVRFVlZlA3VDJCTzgyeTM1Q1QzQmxia0ZKX2JrN3RJRXhhZmxxNXYwZXAzaXYtUkJEeE5UTkx0NEFtaGI4QTNRQUdCQ1FBeHlLVWRqd0xKakNBbGNqVGk4b1lnTWxDazV5UUEK" | base64 -d
