server {
  listen 80;
  server_name localhost;

  access_log  /var/log/nginx/localhost.log main;

  auth_basic "Restricted";
  auth_basic_user_file auth.htpasswd;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri /index.html;
  }
}
