server {
  listen 80;
  server_name localhost;

  access_log  /var/log/nginx/www.example.com.log main;

  location / {
    root /usr/share/nginx/html;
    index index.html index.html;
  }

  location /getData {
    default_type application/json;    # Set type to avoid browser downloading to file
    return 200 "{ \"status\": \"200\", \"message\": \"Successful Response!\" }";
  }

  location /browse {             # new URL path
    alias /usr/share/nginx/html; # Browse this folder
    index index.html;            # Use this file, but if it does *not* exist
    autoindex on;                # Perform directory/file browsing
  }
}
